In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[793, 534, 8692, 5830],
 [793, 534, 8692, 892],
 [793, 6461, 8692, 9966],
 [7682, 6708, 3522, 901, 5864],
 [7682, 6708, 3522, 901, 9502],
 [2713, 793, 132, 8692, 8294],
 [1077, 696, 9321, 901]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [6]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  793  534 8692 5830]
 [   0    0    0    0  793  534 8692  892]
 [   0    0    0    0  793 6461 8692 9966]
 [   0    0    0 7682 6708 3522  901 5864]
 [   0    0    0 7682 6708 3522  901 9502]
 [   0    0    0 2713  793  132 8692 8294]
 [   0    0    0    0 1077  696 9321  901]]


In [7]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2024-10-30 16:32:36.818933: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2024-10-30 16:32:36.818984: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2024-10-30 16:32:36.818994: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2024-10-30 16:32:36.819317: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-10-30 16:32:36.819646: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.predict(embedded_docs)

2024-10-30 16:33:05.388470: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 490ms/step


array([[[ 0.04979526, -0.01247909,  0.03121859, -0.0193382 ,
         -0.01196747, -0.04865336, -0.02243252,  0.00621622,
         -0.0461727 , -0.01433296],
        [ 0.04979526, -0.01247909,  0.03121859, -0.0193382 ,
         -0.01196747, -0.04865336, -0.02243252,  0.00621622,
         -0.0461727 , -0.01433296],
        [ 0.04979526, -0.01247909,  0.03121859, -0.0193382 ,
         -0.01196747, -0.04865336, -0.02243252,  0.00621622,
         -0.0461727 , -0.01433296],
        [ 0.04979526, -0.01247909,  0.03121859, -0.0193382 ,
         -0.01196747, -0.04865336, -0.02243252,  0.00621622,
         -0.0461727 , -0.01433296],
        [-0.02110341, -0.00481449, -0.03117601,  0.04583794,
          0.04199653, -0.02230185,  0.02786677,  0.00172628,
         -0.0232669 , -0.03257655],
        [ 0.04625947,  0.01868013,  0.02815323,  0.02383769,
         -0.02428604, -0.00120524,  0.00183617,  0.01095964,
         -0.01428755,  0.01906172],
        [-0.0232669 , -0.00651645, -0.01862882,  0.0

In [12]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 66ms/step


array([[ 0.04979526, -0.01247909,  0.03121859, -0.0193382 , -0.01196747,
        -0.04865336, -0.02243252,  0.00621622, -0.0461727 , -0.01433296],
       [ 0.04979526, -0.01247909,  0.03121859, -0.0193382 , -0.01196747,
        -0.04865336, -0.02243252,  0.00621622, -0.0461727 , -0.01433296],
       [ 0.04979526, -0.01247909,  0.03121859, -0.0193382 , -0.01196747,
        -0.04865336, -0.02243252,  0.00621622, -0.0461727 , -0.01433296],
       [ 0.04979526, -0.01247909,  0.03121859, -0.0193382 , -0.01196747,
        -0.04865336, -0.02243252,  0.00621622, -0.0461727 , -0.01433296],
       [-0.02110341, -0.00481449, -0.03117601,  0.04583794,  0.04199653,
        -0.02230185,  0.02786677,  0.00172628, -0.0232669 , -0.03257655],
       [ 0.04625947,  0.01868013,  0.02815323,  0.02383769, -0.02428604,
        -0.00120524,  0.00183617,  0.01095964, -0.01428755,  0.01906172],
       [-0.0232669 , -0.00651645, -0.01862882,  0.00245819, -0.01582672,
        -0.03658286, -0.01159277,  0.03493971